# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Topics',
        ),
    ]
