# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_auto_20170624_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='myapp/images')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Student')),
            ],
        ),
    ]
