# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_auto_20170624_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='myapp/images'),
        ),
    ]
